rm -f :2eDS_Store
rm -f */:2eDS_Store
rm -f */*/:2eDS_Store
rm -f */*/*/:2eDS_Store
rm -f */*/*/*/:2eDS_Store
rm -f */*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/*/*/*/*/:2eDS_Store
rm -f */*/*/*/*/*/*/*/*/*/*/*/*/:2eDS_Store

rm -rf .AppleDouble
rm -rf */.AppleDouble
rm -rf */*/.AppleDouble
rm -rf */*/*/.AppleDouble
rm -rf */*/*/*/.AppleDouble
rm -rf */*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/*/*/*/*/.AppleDouble
rm -rf */*/*/*/*/*/*/*/*/*/*/*/*/.AppleDouble

